// Generated by CoffeeScript 1.10.0
"use strict";
var ganglere;

window.game = null;

ganglere = require('./ganglere');

window.addEventListener('load', function() {
  if (typeof FastClick !== "undefined" && FastClick !== null) {
    FastClick.attach(document.body);
  }
  return setTimeout(function() {
    document.getElementById("logo").style.display = 'none';
    document.getElementById("title").style.display = 'none';
    document.body.style.backgroundColor = 'black';
    return new ganglere('game');
  }, 1000);
}, false);
