// Generated by CoffeeScript 1.10.0
"use strict";
var ganglere;

ganglere = require('../ganglere');

ganglere.AI = (function() {
  var hunt, reshuffle, wander;

  AI.prototype.game = null;

  reshuffle = [
    {
      x: -1,
      y: 0
    }, {
      x: 1,
      y: 0
    }, {
      x: 0,
      y: -1
    }, {
      x: 0,
      y: 1
    }
  ];

  wander = function() {
    var i, j, t;
    i = reshuffle.length;
    while (--i > 0) {
      j = ~~(Math.random() * (i + 1));
      t = reshuffle[j];
      reshuffle[j] = reshuffle[i];
      reshuffle[i] = t;
    }
    return reshuffle;
  };

  hunt = function(deltaX, deltaY) {
    return [
      {
        x: -1,
        y: 0
      }, {
        x: 1,
        y: 0
      }, {
        x: 0,
        y: -1
      }, {
        x: 0,
        y: 1
      }
    ].map(function(direction) {
      return {
        x: direction.x,
        y: direction.y,
        distance: Math.pow(deltaX + direction.x, 2) + Math.pow(deltaY + direction.y, 2)
      };
    }).sort(function(a, b) {
      return b.distance - a.distance;
    });
  };

  function AI(game) {
    this.game = game;
  }

  AI.prototype.wander = function(actor) {
    var direction, k, len, ref, results;
    ref = wander();
    results = [];
    for (k = 0, len = ref.length; k < len; k++) {
      direction = ref[k];
      if (this.game.moveTo(actor, direction)) {
        break;
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  AI.prototype.hunt = function(actor, deltaX, deltaY) {
    var direction, k, len, ref, results;
    ref = hunt(deltaX, deltaY);
    results = [];
    for (k = 0, len = ref.length; k < len; k++) {
      direction = ref[k];
      if (this.game.moveTo(actor, direction)) {
        break;
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  return AI;

})();
