// Generated by CoffeeScript 1.10.0
"use strict";
var ganglere,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ganglere = require("../ganglere");

ganglere.GameOver = (function(superClass) {
  extend(GameOver, superClass);

  function GameOver() {
    this.create = bind(this.create, this);
    return GameOver.__super__.constructor.apply(this, arguments);
  }

  GameOver.prototype.create = function() {
    var gameOver;
    gameOver = this.add.text(0, 0, "Game Over\nCtrl+r to restart", {
      fill: "#e22",
      align: "center"
    });
    gameOver.fixedToCamera = true;
    return gameOver.cameraOffset.setTo(0, 0);
  };

  return GameOver;

})(Phaser.State);
