// Generated by CoffeeScript 1.10.0
"use strict";
var ganglere,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ganglere = require('../ganglere');

ganglere.Player = (function(superClass) {
  extend(Player, superClass);

  function Player(game, x, y) {
    Player.__super__.constructor.call(this, game, x, y, game.player.sprite);
    this.hp = game.player.hp;
    this.damage = game.player.damage;
    this.isPlayer = true;
  }

  return Player;

})(ganglere.Actor);
