// Generated by CoffeeScript 1.10.0
"use strict";
var ganglere,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ganglere = require('../ganglere');

ganglere.Scores = (function(superClass) {
  extend(Scores, superClass);

  function Scores() {
    return Scores.__super__.constructor.apply(this, arguments);
  }

  Scores.prototype.preload = function() {};

  Scores.prototype.create = function() {
    this.add.sprite(0, 0, 'background');
    this.add.sprite(0, 0, 'icon');
    this.add.sprite(0, 10, 'quote');
    return this.add.button(this.game.width / 2 - 38, this.game.height - 80, 'backButton', this.goBack, this, 2, 1, 0);
  };

  Scores.prototype.goBack = function() {
    return this.state.start('Intro', true, false);
  };

  return Scores;

})(Phaser.State);
