// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../game');

Game.Glyph = (function() {
  function Glyph(properties) {
    properties = properties || {};
    this._char = properties["character"] || " ";
    this._foreground = properties["foreground"] || "white";
    this._background = properties["background"] || "black";
  }

  Glyph.prototype.getChar = function() {
    return this._char;
  };

  Glyph.prototype.getBackground = function() {
    return this._background;
  };

  Glyph.prototype.getForeground = function() {
    return this._foreground;
  };

  Glyph.prototype.getRepresentation = function() {
    return "%c{" + this._foreground + "}%b{" + this._background + "}" + this._char + "%c{white}%b{black}";
  };

  return Glyph;

})();
