// Generated by CoffeeScript 1.7.1
var Game,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Game = require('./../game');

Game.Item = (function(_super) {
  __extends(Item, _super);

  function Item(properties) {
    properties = properties || {};
    Item.__super__.constructor.call(this, properties);
    return;
  }

  return Item;

})(Game.DynamicGlyph);

Game.ItemMixins = {};
