// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../game');

Game.Repository = (function() {
  function Repository(name, ctor) {
    this._name = name;
    this._templates = {};
    this._ctor = ctor;
    this._randomTemplates = {};
    return;
  }

  Repository.prototype.define = function(name, template, options) {
    var disableRandomCreation;
    this._templates[name] = template;
    disableRandomCreation = options && options["disableRandomCreation"];
    if (!disableRandomCreation) {
      this._randomTemplates[name] = template;
    }
  };

  Repository.prototype.create = function(name, extraProperties) {
    var key, template;
    if (!this._templates[name]) {
      throw new Error("No template named '" + name + "' in repository '" + this._name + "'");
    }
    template = Object.create(this._templates[name]);
    if (extraProperties) {
      for (key in extraProperties) {
        template[key] = extraProperties[key];
      }
    }
    return new this._ctor(template);
  };

  Repository.prototype.createRandom = function() {
    return this.create(Object.keys(this._randomTemplates).random());
  };

  return Repository;

})();
