// Generated by CoffeeScript 1.7.1
var Game,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Game = require('./../game');

Game.Tile = (function(_super) {
  __extends(Tile, _super);

  function Tile(properties) {
    properties = properties || {};
    Tile.__super__.constructor.call(this, properties);
    this._walkable = properties["walkable"] || false;
    this._diggable = properties["diggable"] || false;
    this._blocksLight = (properties["blocksLight"] !== undefined ? properties["blocksLight"] : true);
    this._description = properties["description"] || "";
  }

  Tile.prototype.isWalkable = function() {
    return this._walkable;
  };

  Tile.prototype.isDiggable = function() {
    return this._diggable;
  };

  Tile.prototype.isBlockingLight = function() {
    return this._blocksLight;
  };

  Tile.prototype.getDescription = function() {
    return this._description;
  };

  Tile.nullTile = new Tile({
    description: "(unknown)"
  });

  Tile.floorTile = new Tile({
    character: ".",
    walkable: true,
    blocksLight: false,
    description: "A cave floor"
  });

  Tile.wallTile = new Tile({
    character: "#",
    foreground: "goldenrod",
    diggable: true,
    description: "A cave wall"
  });

  Tile.stairsUpTile = new Tile({
    character: "<",
    foreground: "white",
    walkable: true,
    blocksLight: false,
    description: "A rock staircase leading upwards"
  });

  Tile.stairsDownTile = new Tile({
    character: ">",
    foreground: "white",
    walkable: true,
    blocksLight: false,
    description: "A rock staircase leading downwards"
  });

  Tile.holeToCavernTile = new Tile({
    character: "O",
    foreground: "white",
    walkable: true,
    blocksLight: false,
    description: "A great dark hole in the ground"
  });

  Tile.waterTile = new Tile({
    character: "~",
    foreground: "blue",
    walkable: false,
    blocksLight: false,
    description: "Murky blue water"
  });

  return Tile;

})(Game.Glyph);
