// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.ItemMixins.Edible = {
  name: "Edible",
  init: function(template) {
    this._foodValue = template["foodValue"] || 5;
    this._maxConsumptions = template["consumptions"] || 1;
    return this._remainingConsumptions = this._maxConsumptions;
  },
  eat: function(entity) {
    if (entity.hasMixin("FoodConsumer")) {
      if (this.hasRemainingConsumptions()) {
        entity.modifyFullnessBy(this._foodValue);
        return this._remainingConsumptions--;
      }
    }
  },
  hasRemainingConsumptions: function() {
    return this._remainingConsumptions > 0;
  },
  describe: function() {
    if (this._maxConsumptions !== this._remainingConsumptions) {
      return "partly eaten " + Game.Item.prototype.describe.call(this);
    } else {
      return this._name;
    }
  },
  listeners: {
    details: function() {
      return [
        {
          key: "food",
          value: this._foodValue
        }
      ];
    }
  }
};
