// Generated by CoffeeScript 1.7.1
"use strict";
var ganglere,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ganglere = require("../ganglere");

ganglere.GameOver = (function(_super) {
  __extends(GameOver, _super);

  function GameOver() {
    this.create = __bind(this.create, this);
    return GameOver.__super__.constructor.apply(this, arguments);
  }

  GameOver.prototype.create = function() {
    var gameOver;
    gameOver = this.add.text(0, 0, "Game Over\nCtrl+r to restart", {
      fill: "#e22",
      align: "center"
    });
    gameOver.fixedToCamera = true;
    return gameOver.cameraOffset.setTo(0, 0);
  };

  return GameOver;

})(Phaser.State);
