// Generated by CoffeeScript 1.7.1
"use strict";
var ganglere,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = ganglere = (function(_super) {
  __extends(ganglere, _super);

  ganglere.prototype.id = '';

  ganglere.prototype.width = 320;

  ganglere.prototype.height = 480;

  ganglere.prototype.renderer = Phaser.AUTO;

  function ganglere(id) {
    this.id = id;
    ganglere.__super__.constructor.call(this, this.width, this.height, this.renderer, this.id);
    this.state.add('Initialize', ganglere.Initialize, false);
    this.state.add('Assets', ganglere.Assets, false);
    this.state.add('Intro', ganglere.Intro, false);
    this.state.add('Credits', ganglere.Credits, false);
    this.state.add('Scores', ganglere.Scores, false);
    this.state.add('Levels', ganglere.Levels, false);
    this.state.add('GameOver', ganglere.GameOver, false);
    this.state.start('Initialize');
  }

  return ganglere;

})(Phaser.Game);

require('./Config');

require('./Random');

require('./AI');

require('./Actor');

require('./Player');

require('./Enemy');

require('./Map');

require('./Assets');

require('./Initialize');

require('./Intro');

require('./Credits');

require('./Scores');

require('./Levels');

require('./GameOver');
