// Generated by CoffeeScript 1.7.1
"use strict";
var ganglere,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ganglere = require('../ganglere');

ganglere.Player = (function(_super) {
  __extends(Player, _super);

  function Player(game, x, y) {
    Player.__super__.constructor.call(this, game, x, y, game.player.sprite);
    this.hp = game.player.hp;
    this.damage = game.player.damage;
    this.isPlayer = true;
  }

  return Player;

})(ganglere.Actor);
