// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.CorpseDropper = {
  name: "CorpseDropper",
  init: function(template) {
    return this._corpseDropRate = template["corpseDropRate"] || 100;
  },
  listeners: {
    onDeath: function(attacker) {
      if (Math.round(Math.random() * 100) <= this._corpseDropRate) {
        return this._map.addItem(this.getX(), this.getY(), this.getZ(), Game.ItemRepository.create("corpse", {
          name: this._name + " corpse",
          foreground: this._foreground
        }));
      }
    }
  }
};
