// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.Equipper = {
  name: "Equipper",
  init: function(template) {
    this._weapon = null;
    return this._armor = null;
  },
  wield: function(item) {
    return this._weapon = item;
  },
  unwield: function() {
    return this._weapon = null;
  },
  wear: function(item) {
    return this._armor = item;
  },
  takeOff: function() {
    return this._armor = null;
  },
  getWeapon: function() {
    return this._weapon;
  },
  getArmor: function() {
    return this._armor;
  },
  unequip: function(item) {
    if (this._weapon === item) {
      this.unwield();
    }
    if (this._armor === item) {
      return this.takeOff();
    }
  }
};
