// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.FoodConsumer = {
  name: "FoodConsumer",
  init: function(template) {
    this._maxFullness = template["maxFullness"] || 1000;
    this._fullness = template["fullness"] || (this._maxFullness / 2);
    return this._fullnessDepletionRate = template["fullnessDepletionRate"] || 1;
  },
  addTurnHunger: function() {
    return this.modifyFullnessBy(-this._fullnessDepletionRate);
  },
  modifyFullnessBy: function(points) {
    this._fullness = this._fullness + points;
    if (this._fullness <= 0) {
      return this.kill("You have died of starvation!");
    } else {
      if (this._fullness > this._maxFullness) {
        return this.kill("You choke and die!");
      }
    }
  },
  getHungerState: function() {
    var perPercent;
    perPercent = this._maxFullness / 100;
    if (this._fullness <= perPercent * 5) {
      return "Starving";
    } else if (this._fullness <= perPercent * 25) {
      return "Hungry";
    } else if (this._fullness >= perPercent * 95) {
      return "Oversatiated";
    } else if (this._fullness >= perPercent * 75) {
      return "Full";
    } else {
      return "Not Hungry";
    }
  }
};
