// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.GiantZombieActor = Game.merge(Game.EntityMixins.TaskActor, {
  init: function(template) {
    Game.EntityMixins.TaskActor.init.call(this, Game.merge(template, {
      tasks: ["growArm", "spawnSlime", "hunt", "wander"]
    }));
    return this._hasGrownArm = false;
  },
  canDoTask: function(task) {
    if (task === "growArm") {
      return this.getHp() <= 20 && !this._hasGrownArm;
    } else if (task === "spawnSlime") {
      return Math.round(Math.random() * 100) <= 10;
    } else {
      return Game.EntityMixins.TaskActor.canDoTask.call(this, task);
    }
  },
  growArm: function() {
    this._hasGrownArm = true;
    this.increaseAttackValue(5);
    return Game.sendMessageNearby(this.getMap(), this.getX(), this.getY(), this.getZ(), "An extra arm appears on the giant zombie!");
  },
  spawnSlime: function() {
    var slime, xOffset, yOffset;
    xOffset = Math.floor(Math.random() * 3) - 1;
    yOffset = Math.floor(Math.random() * 3) - 1;
    if (!this.getMap().isEmptyFloor(this.getX() + xOffset, this.getY() + yOffset, this.getZ())) {
      return;
    }
    slime = Game.EntityRepository.create("slime");
    slime.setX(this.getX() + xOffset);
    slime.setY(this.getY() + yOffset);
    slime.setZ(this.getZ());
    return this.getMap().addEntity(slime);
  },
  listeners: {
    onDeath: function(attacker) {
      return Game.switchScreen(Game.Screen.winScreen);
    }
  }
});
