// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.PlayerStatGainer = {
  name: "PlayerStatGainer",
  groupName: "StatGainer",
  listeners: {
    onGainLevel: function() {
      Game.Screen.gainStatScreen.setup(this);
      return Game.Screen.playScreen.setSubScreen(Game.Screen.gainStatScreen);
    }
  }
};
