// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.PlayerActor = {
  name: "PlayerActor",
  groupName: "Actor",
  act: function() {
    if (this._acting) {
      return;
    }
    this._acting = true;
    this.addTurnHunger();
    if (!this.isAlive()) {
      Game.Screen.playScreen.setGameEnded(true);
      Game.sendMessage(this, "Press [Enter] to continue!");
    }
    Game.refresh();
    this.getMap().getEngine().lock();
    this.clearMessages();
    this._acting = false;
  }
};
