// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.RandomStatGainer = {
  name: "RandomStatGainer",
  groupName: "StatGainer",
  listeners: {
    onGainLevel: function() {
      var statOptions, _results;
      statOptions = this.getStatOptions();
      _results = [];
      while (this.getStatPoints() > 0) {
        statOptions.random()[1].call(this);
        _results.push(this.setStatPoints(this.getStatPoints() - 1));
      }
      return _results;
    }
  }
};
