// Generated by CoffeeScript 1.7.1
var Game;

Game = require('./../../game');

Game.EntityMixins.Sight = {
  name: "Sight",
  groupName: "Sight",
  init: function(template) {
    return this._sightRadius = template["sightRadius"] || 5;
  },
  getSightRadius: function() {
    return this._sightRadius;
  },
  increaseSightRadius: function(value) {
    value = value || 1;
    this._sightRadius += value;
    return Game.sendMessage(this, "You are more aware of your surroundings!");
  },
  canSee: function(entity) {
    var found, otherX, otherY;
    if (!entity || this._map !== entity.getMap() || this._z !== entity.getZ()) {
      return false;
    }
    otherX = entity.getX();
    otherY = entity.getY();
    if ((otherX - this._x) * (otherX - this._x) + (otherY - this._y) * (otherY - this._y) > this._sightRadius * this._sightRadius) {
      return false;
    }
    found = false;
    this.getMap().getFov(this.getZ()).compute(this.getX(), this.getY(), this.getSightRadius(), function(x, y, radius, visibility) {
      if (x === otherX && y === otherY) {
        return found = true;
      }
    });
    return found;
  }
};
